apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-oozie
  labels:
    app: {{ template "hdp.name" . }}-oozie
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
  - port: 11000
    name: httpoozie
  - port: 11001
    name: back
  selector:
    app: {{ template "hdp.name" . }}-oozie
    release: {{ .Release.Name }}
