apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "hdp.fullname" . }}-hue
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "hdp.name" . }}-hue
    spec:
      containers:
        - name: hue
          image: 190742198407.dkr.ecr.us-west-2.amazonaws.com/xl/apachehue:v18 #13
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8888
              name: http
          env:
          - name: HDFS_HIVE_IP
            value: {{ template "hdp.fullname" . }}-hive-server
          - name: HDFS_IP
            value: {{ template "hdp.fullname" . }}-hdfs-nn-0.{{ template "hdp.fullname" . }}-hdfs-nn # {{ template "hdp.fullname" . }}-hdfs-nn
          - name: HDFS_YARN_IP
            value: {{ template "hdp.fullname" . }}-yarn-rm
          - name: HDFS_SQOOP_IP
            value: {{ .Release.Name }}-sqoop
          - name: HDFS_ZOO_IP
            value: {{ .Release.Name }}-zookeeper
          - name: HDFS_HBASE_IP
            value: {{ template "hdp.fullname" . }}-hbase-thrift
          - name: HDFS_OOZIE_IP
            value: {{ .Release.Name }}-oozie
          - name: DB_HOST
            value: {{ template "hdp.fullname" . }}-mysql
          - name: DB_PORT
            value: "3306"
          - name: AWS_ACCESS_KEY
            value: AKIAI62Z2Y32HVFPXNMQ
          - name: AWS_SECRET_KEY
            value: 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
          - name: AWS_REGION
            value: us-west-2
