apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-zookeeper
  labels:
    app: {{ template "hdp.name" . }}-zookeeper
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "hdp.name" . }}-zookeeper
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: zookeeper
        image: 190742198407.dkr.ecr.us-west-2.amazonaws.com/xl/hdp:zoov1.2 #1.1
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 2181
            name: http
        volumeMounts:
        - name: zoodata
          mountPath: /var/lib/zookeeper
        - name: zoologs
          mountPath: /var/log/zookeeper
      volumes:
      - name: zoodata
        persistentVolumeClaim:
          claimName: {{ template "hdp.fullname" . }}-zoodata
      - name: zoologs
        persistentVolumeClaim:
          claimName: {{ template "hdp.fullname" . }}-zoologs
      restartPolicy: Always
