---
# Source: jupyterhub/templates/proxy/networkpolicy.yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jupyterhub
    app.kubernetes.io/version: 4.6.2
    helm.sh/chart: jupyterhub-8.0.1
    app.kubernetes.io/component: proxy
  name: release-name-jupyterhub-proxy
  namespace: "default"
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: release-name
      app.kubernetes.io/name: jupyterhub
      app.kubernetes.io/component: proxy
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - ports:
        - port: 8000
    - ports:
        - port: 8001
