---
# Source: jupyterhub/templates/proxy/service-public.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-jupyterhub-proxy-public
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jupyterhub
    app.kubernetes.io/version: 4.6.2
    helm.sh/chart: jupyterhub-8.0.1
    app.kubernetes.io/component: proxy
spec:
  type: LoadBalancer
  externalTrafficPolicy: "Cluster"
  sessionAffinity: None
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/name: jupyterhub
    app.kubernetes.io/component: proxy
