---
# Source: jupyterhub/templates/proxy/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-jupyterhub-proxy
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jupyterhub
    app.kubernetes.io/version: 4.6.2
    helm.sh/chart: jupyterhub-8.0.1
    app.kubernetes.io/component: proxy
automountServiceAccountToken: false
