---
# Source: jupyterhub/templates/hub/rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-name-jupyterhub-hub
  namespace: "default"
  labels:
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jupyterhub
    app.kubernetes.io/version: 4.1.6
    helm.sh/chart: jupyterhub-8.0.1
    app.kubernetes.io/component: hub
subjects:
  - kind: ServiceAccount
    name: release-name-jupyterhub-hub
    namespace: default
roleRef:
  kind: Role
  name: release-name-jupyterhub-hub
  apiGroup: rbac.authorization.k8s.io
