
{{ if .Values.password }}
apiVersion: v1
kind: Secret
metadata:
  name: jupyter-{{ .Release.Name }}-password-secret
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  password: {{ b64enc .Values.password }}
{{ end }}
