name: mysql
version: 5.7.14
description: Fast, reliable, scalable, and easy to use open-source relational database
  system.
keywords:
- mysql
- database
- sql
home: https://www.mysql.com/
sources:
- https://github.com/
maintainers:
- name: Xenon
engine: gotpl
