apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tensorflow
  labels:
    app: {{ template "tensorflow.name" . }}-tensorflow
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "tensorflow.name" . }}-tensorflow
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: tensorflow
          image: {{ .Values.tensorflow.image }}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8888
              name: http
          env:
            - name: PASSWORD
              value: xtendlabs
