apiVersion: v1
kind: Service
metadata:
  name: {{ template "cp-kafka.fullname" . }}-headless
  labels:
    app: {{ template "cp-kafka.name" . }}
    chart: {{ template "cp-kafka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 9092
      name: broker
  clusterIP: None
  selector:
    app: {{ template "cp-kafka.name" . }}
    release: {{ .Release.Name }}
    type: {{ .Values.type }}
    workspace_id: {{ .Values.workspace_id | quote }}
    user_id: {{ .Values.user_id | quote }}
    user_name: {{ .Values.user_name | quote }}