apiVersion: v1
description: Web-based notebook that enables data-driven, interactive data analytics and collaborative documents with SQL, Scala and more.
name: jupyter-notebook
version: 1.0.0
appVersion: 0.7.2
home: https://zeppelin.apache.org/
sources:
- https://github.com/apache/zeppelin
maintainers:
- name: danisla
  email: disla@google.com
