apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jupyter
  labels:
    name: {{ template "jupyter.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
  selector:
    app: {{ template "jupyter.name" . }}
    release: {{ .Release.Name }}
