# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

commonlabels:
  app.kubernetes.io/version: "0.1"
  app.kubernetes.io/managed-by: helm
  app.kubernetes.io/contact: nirmal
  app.kubernetes.io/env: dev
  app.kubernetes.io/project: neuronlabs
  app.kubernetes.io/tier: backend
  app.kubernetes.io/requested-by: harpreet

Master:
  Name: master
  Image: "dr.xenon.team/sl_softwares/spark:sparkv1.1" #1.0
  Replicas: 1
  Component: "spark-master"
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
  # Cpu: "100m"
  # Memory: "512Mi"
  initialDelaySeconds: 25
  timeoutSeconds: 1
  # Set Master JVM memory. Default 1g
  # DaemonMemory: 1g
  ServiceType: ClusterIP # LoadBalancer


Worker:
  Name: worker
  Image: "dr.xenon.team/sl_softwares/spark:sparkworkerv1.1" #1.0
  Replicas: 1
  Component: "spark-worker"
  resources:
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
  # Cpu: "100m"
  # Memory: "512Mi"
  initialDelaySeconds: 30
  timeoutSeconds: 1

  # Set Worker JVM memory. Default 1g
  # DaemonMemory: 1g
  # Set how much total memory workers have to give executors
  # ExecutorMemory: 1g

ingress:
  enabled: false
  class: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
  domainName: neuronlabs.stpi.in

  tls: []
