kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "zeppelin.fullname" . }}-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["create", "get", "update", "patch", "list", "delete", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings"]
  verbs: ["bind", "create", "get", "update", "patch", "list", "delete", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "zeppelin.fullname" . }}-role-binding
subjects:
- kind: ServiceAccount
  name: {{ include "zeppelin.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "zeppelin.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
