kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "zeppelin.fullname" . }}-role-bindin
subjects:
- kind: ServiceAccount
  name: {{ include "zeppelin.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "zeppelin.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
