apiVersion: v1
kind: Service
metadata:
  name: {{ include "zeppelin.fullname" . }}
  labels:
    {{- include "zeppelin.labels" . | nindent 4 }}
spec:
  # type: {{ .Values.service.type }}
  type: NodePort
  ports:
    - name: http
      port: {{ .Values.service.port }}
    - name: rpc            # port name is referenced in the code. So it shouldn't be changed.
      port: 12320
  selector:
    workspace_id: {{ .Values.workspace_id | quote }}
    user_id: {{ .Values.user_id | quote }}
    user_name: {{ .Values.user_name | quote}}
    {{- include "zeppelin.selectorLabels" . | nindent 4 }}
