{{- if .Values.authentication.enabled }}
{{- if eq .Values.authentication.userCredentialSecretName "" }}
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "zeppelin.fullname" . }}-secret
type: Opaque
data:
  username: {{ .Values.authentication.username  | b64enc | quote }}
  {{- if .Values.authentication.password }}
  password: {{ .Values.authentication.password  | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
