apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}-headless
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    type: {{ .Values.type}}
    workspace_id: {{ .Values.workspace_id}}
spec:
  type: ClusterIP
  clusterIP: None
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
