{{- if .Values.Master.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "spark.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    {{- range $key, $value := .Values.Master.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .Release.Name }}.{{ .Values.Master.ingress.domainName}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "spark.fullname" . }}
          servicePort: 4040
{{- end -}}
