{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-spark-master
  labels:
    app: {{ template "spark.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .Release.Name }}.{{ .Values.ingress.domainName}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "spark.fullname" . }}
          servicePort: 8080
{{- end -}}
