{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "common.names.fullname" . }}
{{- with .Values.metrics.prometheusRule.namespace }}
  namespace: {{ . }}
{{- end }}
  labels:
  {{- include "common.labels.standard" . | nindent 4 }}
  {{ .Values.workspace_id}}
  {{- with .Values.metrics.prometheusRule.additionalLabels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.commonAnnotations }}
    type: {{ .Values.type}}
    workspace_id: {{ .Values.workspace_id}}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
{{- with .Values.metrics.prometheusRule.rules }}
  groups:
    - name: {{ include "common.names.fullname" . }}
      rules: {{ tpl (toYaml .) $ | nindent 8 }}
{{- end }}
{{- end }}
