apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-openrefine
  labels:
    app: openrefine
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 3333
    targetPort: 3333
  selector:
    app: openrefine
    release: {{ .Release.Name }}
