apiVersion: v1
kind: Service
metadata:
  name: {{ template "bigdata.fullname" . }}-hive-server
  labels:
    app: {{ template "bigdata.name" . }}-hive-server
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  - name: hiveserver
    port: 10000
    targetPort: 10000
  - name: other
    port: 10002
    targetPort: 10002    
  selector:
    app: {{ template "bigdata.name" . }}-hive-server
    release: {{ .Release.Name }}
status:
  loadBalancer: {}
