# Service to access the yarn web ui
apiVersion: v1
kind: Service
metadata:
  name: {{ template "bigdata.fullname" . }}-yarn-ui
  labels:
    app: {{ template "bigdata.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: yarn-ui
spec:
  ports:
  - port: 8088
    name: yarnweb
  type: NodePort
  selector:
    app: {{ template "bigdata.name" . }}
    component: yarn-rm
