apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sink
  labels:
    app: {{ template "bigdata.name" . }}-sink
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "bigdata.name" . }}-sink
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: flume
          image: {{ .Values.sink.image }}
          imagePullPolicy: "IfNotPresent"
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sink
  labels:
    app: {{ template "bigdata.name" . }}-sink
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports: null
  selector:
    app: {{ template "bigdata.name" . }}-sink
    release: {{ .Release.Name }}
